GitHub: github.com/karthik-xd // LinkedIn: linkedin.com/in/karthikeyan-mp-19b17a350

In [33]:
import requests as r
import pandas as pd
import re
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [8]:
apikey="16addb87af241cb14d7d06b3eee1b572"
url='https://api.themoviedb.org/3/trending/movie/week'
respond=r.get(url,params={"api_key":apikey})

In [9]:
st=respond.status_code
if st == 200:
    print("Code: 200 Success! Data is ready")
elif st == 401:
     print("Code: 401 Wrong! API key")
elif st == 404:
     print("Code: 404 Wrong URL address")
elif st == 429:
     print("Code: 429 Too many requests")
else :
    print("Something went wrong!!")

Code: 200 Success! Data is ready

In [10]:
data = respond.json()
print(f"Total Pages: {data['total_pages']}")
print(f"Total Movies: {data['total_results']}")

Total Pages: 500
Total Movies: 10000

In [11]:
al_movi=[]
num_page=30
c=0
d=0
for pages in range(1,num_page+1):
    url='https://api.themoviedb.org/3/trending/movie/week'
    respond=r.get(url,params={"api_key":apikey,"page":pages})
    st=respond.status_code
    if st == 200:
        c=c+1
        #print("Code: 200 Success! Datapage_ADDED",pages)
        dat = respond.json()
        dat=dat["results"]
        al_movi.extend(dat)
    else: 
        print("having error !!. So data will not be extended !")
        d=d+1
print("Success pages:",c)
print("Error pages:",d)

Success pages: 30
Error pages: 0

In [12]:
df=pd.DataFrame(al_movi)
df

,adult,backdrop_path,id,title,original_title,overview,poster_path,media_type,original_language,genre_ids,popularity,release_date,softcore,video,vote_average,vote_count
0,False,/xBT0oNq6rsTFv4SxG5uGRIEOrq6.jpg,936075,Michael,Michael,"Discover the story of Michael Jackson, one of ...",/3Qud19bBUrrJAzy0Ilm8gRJlJXP.jpg,movie,en,"[10402, 18]",113.6273,2026-04-22,False,False,7.305,105
1,False,/sS3zGYFPcfM5pArVNWl6qLyaSmU.jpg,980431,Avatar Aang: The Last Airbender,Avatar Aang: The Last Airbender,"Avatar Aang, the world's last Airbender, learn...",/29Jdsak3SrwGds5k1t43kH6Khed.jpg,movie,en,"[16, 28, 12, 14]",277.9116,2026-10-09,False,False,0.000,0
2,False,/8Tfys3mDZVp4tNoH2ktm06a0Tau.jpg,687163,Project Hail Mary,Project Hail Mary,Science teacher Ryland Grace wakes up on a spa...,/yihdXomYb5kTeSivtFndMy5iDmf.jpg,movie,en,"[878, 12]",206.8121,2026-03-15,False,False,8.218,1674
3,False,/u8DU5fkLoM5tTRukzPC31oGPxaQ.jpg,83533,Avatar: Fire and Ash,Avatar: Fire and Ash,In the wake of the devastating war against the...,/aabwWZWx6z1aYP4PX2ADvbDKktd.jpg,movie,en,"[878, 12, 14]",246.3145,2025-12-17,False,False,7.376,2698
4,False,/kxQiIJ4gVcD3K6o14MJ72p5yRcE.jpg,1226863,The Super Mario Galaxy Movie,The Super Mario Galaxy Movie,Having thwarted Bowser's previous plot to marr...,/eJGWx219ZcEMVQJhAgMiqo8tYY.jpg,movie,en,"[10751, 35, 12, 14, 16]",613.4012,2026-04-01,False,False,6.745,580
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
593,False,/eyIxeio4UhUen5XJY67Dhs6rSJV.jpg,1555232,Just a Job,不过是上班,The film follows a protagonist trapped in a su...,/ocOIxHfnxaIzrDdZRAgRnnCPS0S.jpg,movie,zh,[35],0.7288,2026-01-10,False,False,5.500,2
594,False,/3bFyBL1gFghrWH3FG0wNwZc1BGp.jpg,1257406,Two Prosecutors,Zwei Staatsanwälte,"In 1937, amidst Stalin's Great Terror, a newly...",/dU46ROG7HoP7biPtntaMTjkGbU6.jpg,movie,ru,"[18, 9648, 53, 36]",1.8335,2025-10-03,False,False,6.800,24
595,False,None,1368492,The Wolf and the Lamb,The Wolf and the Lamb,A widowed teacher in a 1870s Montana mining ca...,/cJs61pTY5F7zJjE3WJgLc08zpAe.jpg,movie,en,"[53, 37, 27]",1.4715,2026-04-24,False,False,0.000,0
596,False,/sQRWbq6nmrPrJCIIxbSB6bYvw5e.jpg,1133093,Lilly,Lilly,Based on the inspiring true story of Lilly Led...,/kkvJu6Dz7umgBHgpCiTyh3rPFhC.jpg,movie,en,"[18, 36]",2.0930,2025-05-09,False,False,7.100,14
597,False,/7N7CtZftqEvgojR3QloukU0oWPg.jpg,516729,Paddington in Peru,Paddington in Peru,Paddington travels to Peru to visit his belove...,/1ffZAucqfvQu36x1C49XfOdjuOG.jpg,movie,en,"[10751, 35, 12]",8.2493,2024-11-08,False,False,6.818,670

In [13]:
df = df.drop_duplicates(subset='id')

In [22]:
df.loc[:, 'release_date'] = pd.to_datetime(df['release_date'], errors='coerce')

In [23]:
df.loc[:, 'year'] = df['release_date'].dt.year
df.loc[:, 'month'] = df['release_date'].dt.month_name()

In [24]:
df

,adult,backdrop_path,id,title,original_title,overview,poster_path,media_type,original_language,genre_ids,popularity,release_date,softcore,video,vote_average,vote_count,year,month
0,False,/xBT0oNq6rsTFv4SxG5uGRIEOrq6.jpg,936075,Michael,Michael,"Discover the story of Michael Jackson, one of ...",/3Qud19bBUrrJAzy0Ilm8gRJlJXP.jpg,movie,en,"[10402, 18]",113.6273,2026-04-22,False,False,7.305,105,2026.0,April
1,False,/sS3zGYFPcfM5pArVNWl6qLyaSmU.jpg,980431,Avatar Aang: The Last Airbender,Avatar Aang: The Last Airbender,"Avatar Aang, the world's last Airbender, learn...",/29Jdsak3SrwGds5k1t43kH6Khed.jpg,movie,en,"[16, 28, 12, 14]",277.9116,2026-10-09,False,False,0.000,0,2026.0,October
2,False,/8Tfys3mDZVp4tNoH2ktm06a0Tau.jpg,687163,Project Hail Mary,Project Hail Mary,Science teacher Ryland Grace wakes up on a spa...,/yihdXomYb5kTeSivtFndMy5iDmf.jpg,movie,en,"[878, 12]",206.8121,2026-03-15,False,False,8.218,1674,2026.0,March
3,False,/u8DU5fkLoM5tTRukzPC31oGPxaQ.jpg,83533,Avatar: Fire and Ash,Avatar: Fire and Ash,In the wake of the devastating war against the...,/aabwWZWx6z1aYP4PX2ADvbDKktd.jpg,movie,en,"[878, 12, 14]",246.3145,2025-12-17,False,False,7.376,2698,2025.0,December
4,False,/kxQiIJ4gVcD3K6o14MJ72p5yRcE.jpg,1226863,The Super Mario Galaxy Movie,The Super Mario Galaxy Movie,Having thwarted Bowser's previous plot to marr...,/eJGWx219ZcEMVQJhAgMiqo8tYY.jpg,movie,en,"[10751, 35, 12, 14, 16]",613.4012,2026-04-01,False,False,6.745,580,2026.0,April
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
593,False,/eyIxeio4UhUen5XJY67Dhs6rSJV.jpg,1555232,Just a Job,不过是上班,The film follows a protagonist trapped in a su...,/ocOIxHfnxaIzrDdZRAgRnnCPS0S.jpg,movie,zh,[35],0.7288,2026-01-10,False,False,5.500,2,2026.0,January
594,False,/3bFyBL1gFghrWH3FG0wNwZc1BGp.jpg,1257406,Two Prosecutors,Zwei Staatsanwälte,"In 1937, amidst Stalin's Great Terror, a newly...",/dU46ROG7HoP7biPtntaMTjkGbU6.jpg,movie,ru,"[18, 9648, 53, 36]",1.8335,2025-10-03,False,False,6.800,24,2025.0,October
595,False,None,1368492,The Wolf and the Lamb,The Wolf and the Lamb,A widowed teacher in a 1870s Montana mining ca...,/cJs61pTY5F7zJjE3WJgLc08zpAe.jpg,movie,en,"[53, 37, 27]",1.4715,2026-04-24,False,False,0.000,0,2026.0,April
596,False,/sQRWbq6nmrPrJCIIxbSB6bYvw5e.jpg,1133093,Lilly,Lilly,Based on the inspiring true story of Lilly Led...,/kkvJu6Dz7umgBHgpCiTyh3rPFhC.jpg,movie,en,"[18, 36]",2.0930,2025-05-09,False,False,7.100,14,2025.0,May
597,False,/7N7CtZftqEvgojR3QloukU0oWPg.jpg,516729,Paddington in Peru,Paddington in Peru,Paddington travels to Peru to visit his belove...,/1ffZAucqfvQu36x1C49XfOdjuOG.jpg,movie,en,"[10751, 35, 12]",8.2493,2024-11-08,False,False,6.818,670,2024.0,November

In [35]:

df = df.copy()

df.loc[:, 'overview'] = df['overview'].fillna('')

df.loc[:, 'genre_metadata'] = df['genre_ids'].apply(lambda x: ' '.join(map(str, x)))

df.loc[:, 'soup'] = (df['overview'] + " " + df['genre_metadata']).str.lower()

def clean_text(text):
    return re.sub(r'[^a-zA-Z0-9\s]', '', str(text))

df.loc[:, 'soup'] = df['soup'].apply(clean_text)


tfidf = TfidfVectorizer(stop_words='english')


tfidf_matrix = tfidf.fit_transform(df['soup'])


cosine_sim = cosine_similarity(tfidf_matrix, tfidf_matrix)

def clean_input(text):
    """Helper to clean user input so 'Avatar!' matches 'avatar'"""
    return re.sub(r'[^a-zA-Z0-9\s]', '', str(text)).lower().strip()

def recommend_expert(movie_list):
    valid_indices = []
    missing_movies = []

   
    df_clean_titles = df['title'].apply(clean_input)
    
    
    for movie in movie_list:
        clean_name = clean_input(movie)
        match = df[df_clean_titles == clean_name]
        
        if not match.empty:
            valid_indices.append(match.index[0])
        else:
            missing_movies.append(movie)

    
    if missing_movies:
        print(f" Note: These were not in the trending list: {', '.join(missing_movies)}")

    if not valid_indices:
        return " I couldn't find any of those movies to base a recommendation on."

    blended_scores = cosine_sim[valid_indices].mean(axis=0)
    
    sim_scores = list(enumerate(blended_scores))
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

    final_indices = []
    for i, score in sim_scores:
        if i not in valid_indices:
            final_indices.append(i)
        if len(final_indices) == 6:
            break

    print(f"\n Predictions based on common features of {len(valid_indices)} movies:")
    return df[['title', 'vote_average', 'release_date']].iloc[final_indices]

Give the movie you watched

In [37]:
my_selections = ["Avatar", "Project Hail Mary", "Apex", "The Crow",'Michael',"Lee Cronin's The Mummy"] 

results = recommend_expert(my_selections)
print(results)

 Note: These were not in the trending list: The Crow

 Predictions based on common features of 5 movies:
                               title  vote_average release_date
86                    Evil Dead Burn         0.000   2026-07-08
90                       Die My Love         6.168   2025-10-06
455                 The Desert Child         7.875   2026-04-08
528                   Parallel Tales         0.000   2026-05-14
487                        Happy Raj         5.000   2026-03-27
301  BTS THE COMEBACK LIVE | ARIRANG         9.159   2026-03-21